name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: backend

    - name: Run Linting (Flake8)
      run: pip install flake8 && flake8 .
      working-directory: backend

    - name: Run Tests
      run: python manage.py test
      working-directory: backend

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download backend build artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: backend/

    - name: Deploy to production
      run: echo "Deploying backend to production..."
      # Add your deployment steps here. This could involve:
      # - SSH into a server and running deployment scripts
      # - Using a cloud provider's CLI (e.g., AWS CLI, Azure CLI, gcloud CLI)
      # - Interacting with a CI/CD tool like ArgoCD, Spinnaker, or Jenkins
      # Example: ./ci-cd/scripts/deploy_backend.sh
