name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: frontend

    - name: Run Tests
      run: npm test
      working-directory: frontend

    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download frontend build artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/build

    - name: Deploy to production
      run: echo "Deploying frontend to production..."
      # Add your deployment steps here. This could involve:
      # - Deploying to a static hosting service (e.g., Netlify, Vercel, GitHub Pages)
      # - Uploading to an S3 bucket
      # - Using a cloud provider's CLI
