name: ML CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "ml/**"
  pull_request:
    branches:
      - main
    paths:
      - "ml/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ml

      - name: Run Tests
        run: python -m pytest
        working-directory: ml

      - name: Archive model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-models
          path: ml/models/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: ml-models
          path: ml/models/

      - name: Deploy ML models
        run: echo "Deploying ML models to production..."
        # Add your ML model deployment steps here. This could involve:
        # - Pushing models to a model registry (e.g., MLflow, Sagemaker)
        # - Updating serving endpoints
        # - Running data pipelines
